### ISSUE TITLE
[Question] generate positive only numbers

### ISSUE THREAD

**Issue by MarcMagnin** [spaolacci/murmur3#18]
Hi,
Thanks a lot for this library.
Is there is a way to generate positive number only?

Many thanks,
Marc

**Comment by spaolacci** [comment]
Hi Marc,

I'm not sure I get the question right. For example,`Sum32()` returns an `uint32`, which is postive. Same goes for `Sum64` with `uint64`.

Can you please further describe what's your having trouble with?

Thanks,
Seb

**Comment by snirad** [comment]
is it possible to return signed  numbers ?

**Comment by DigitalMarc** [comment]
Well, I'm not sure why I wrote that at the time... ;) Probably because I was looking as some conversion of the uint32 to int32 after some Avro serialization...
Many thanks!
