### ISSUE TITLE
GoModules incompatible release versions

### ISSUE THREAD

**Issue by im-kulikov** [spaolacci/murmur3#24]
On [release page](https://github.com/spaolacci/murmur3/releases) versions have form `vX.Y`, by GoModules cannot work with that form.. 

It will be nice if you add two additional tags on same revisions in the form of `vX.Y.Z`
- `v1.1.0 -> v1.1 (9f5d223)` 
- `v1.0.0 -> v1.0 (0d12bf8)`

Thanks!

**Comment by spaolacci** [comment]
I just updated the tags. They had no particular purpose nor semantic till now, glad that Go eventually had versioned modules.

Thanks for the report.

**Comment by im-kulikov** [comment]
@spaolacci thanks
